### ISSUE TITLE
Refactor to using new `tracing_subscriber` `Registry` API

### ISSUE THREAD

**Issue by samscott89** [inanna-malick/tracing-honeycomb#2]
First of all, thanks for writing this crate! I hope the following is helpful.

As of https://github.com/tokio-rs/tracing/pull/420, tracing now provides an out of the box subscriber to keep track of spans.

Would it make sense to split out the span/trace tracking + timing logic which you have here to a separate `Layer` implementation, which can then be combined with `Registry`, and use the `LookupSpan` extension trait to store/retrieve fields?

This would provide the main machinery necessary to do anything, whether honeycomb, open-tracing, or other. And using libhoney, zipkin traces + the honeycomb exporter, or just plain JSON can all be added as, again, different layers.

For example, we end up with something like this:

```
    let audit_layer = AuditLayer::default();
    let honey_layer = tracer::HoneycombTracer::new("test-tracing.log");
    let zipkin_layer = tracer::ZipkinTracer::new("http://localhost:9411/api/v2/spans");
    let trace_layer = tracer::TraceLayer::default();
    let fmt_layer = get_fmt_layer();

    let subscriber = audit_layer
        .and_then(trace_layer)
        .and_then(honey_layer)
        .and_then(zipkin_layer)
        .and_then(fmt_layer) // format layer must be bottom layer, since it filters
        .with_subscriber(Registry::default());
```
`trace_layer` is the instrumentation actually adding span IDs and tracking duration
`honey_layer` is outputting json to a file, watched by honeytail.
`ziplin_layer` writing zipkin events to localhost:9411
`fmt_layer` is writing log output to stdout

**Comment by inanna-malick** [comment]
That sounds great, I'm going to try to finish up some documentation tasks (at this point, I really need to just write up docs as a priority - I keep finding excuses to put that off :) )  so I can get a 0.0.1 out after which I'll refactor it to use the audit layer. I really like this pattern, btw - thanks for the post!

**Comment by samscott89** [comment]
No problem. Just to clarify, the audit layer is just another layer implementation we have internally. It's not related to the other parts :)

Although perhaps the trace layer should be top of the stack.....

**Comment by inanna-malick** [comment]
Ah, right - I had the composition order backwards. `Registry::default()` provides the base subscriber, right? (with `fmt` being the first layer on top of it so it can filter)

**Comment by samscott89** [comment]
Yep that's right!

And the `Registry` allows you to store a bunch of data in the spans, which is where you can track things like trace/span IDs without needing to create your own local storage.

In my example, I have `TraceLayer` which will create span IDs on `on_enter`, and the `Zipkin/HoneycombLayer`s will emit the trace data on `on_exit`.

**Comment by inanna-malick** [comment]
That's really cool, is this in the currently released version of tracing or in some yet-to-be-released future version?

**Comment by samscott89** [comment]
Yup, just on master for now. You can see the docs for registry here: https://tracing-rs.netlify.com/tracing_subscriber/registry/index.html

There's a few follow ups to issue 420 I think before it gets into a release.

**Comment by davidbarsky** [comment]
(The registry has made it into the tracing 0.2.0-alpha.1 release, you don’t need to rely on master)

**Comment by inanna-malick** [comment]
Awesome - I finally got v0.0.1 of this published, I'll start refactoring it to use the registry soon.

**Comment by davidbarsky** [comment]
`tracing-subscriber`, not `tracing`, is released as an alpha, excuse me! https://crates.io/crates/tracing-subscriber/0.2.0-alpha.1

And feel free to ping me on Discord if you have any questions!

**Comment by davidbarsky** [comment]
(No rush, obviously!)

**Comment by hawkw** [comment]
FWIW, the registry is now in a stable `tracing-subscriber` release: [0.2.0](https://crates.io/crates/tracing-subscriber/0.2.0).

**Comment by inanna-malick** [comment]
Awesome, thanks! I was mostly delaying while I thought through how to handle refactoring some identity stuff (tldr; I'm trans and will be releasing the next version of this library using my newly-updated name/github acct name/etc)

**Comment by inanna-malick** [comment]
implemented & released this a while back, sorry for leaving the issue open so long but \*gestures at current state of the US\*
