### ISSUE TITLE
Documented link to documentation returns HTTP 404

### ISSUE THREAD

**Issue by mx00s** [inanna-malick/tracing-honeycomb#4]
Doc links at https://crates.io/crates/honeycomb-tracing point to https://pkinsky.github.io/honeycomb-tracing/honeycomb_tracing/.

*EDIT*: The license link is also broken: https://github.com/inanna-malick/honeycomb-tracing/blob/LICENSE-MIT

**Comment by mx00s** [comment]
Apparently the @pkinsky user doesn't exist anymore: https://github.com/pkinsky/

**Comment by inanna-malick** [comment]
sorry, I didn't realize github's post-namechange link redirects are only temporary. I'll update those links to point to the right username.

**Comment by inanna-malick** [comment]
nevermind, I see the issue - I updated the naming convention to match other tracing libraries, the most recent version of this library can be found at https://crates.io/crates/tracing-honeycomb, https://crates.io/crates/tracing-jaeger and https://crates.io/crates/tracing-distributed. Most of the backend-agnostic logic is in tracing-distributed, with honeycomb & jaeger specific implementations and convenience functions in tracing-honeycomb and tracing-jager.

I'm going to look into options for yanking that crate, failing that I'll update it to include a stub readme linking to the correct crate.

**Comment by inanna-malick** [comment]
Given that crates.io does not allow removing crates (by design), I've updated the honeycomb-tracing crate to a stub linking to tracing-honeycomb. https://crates.io/crates/honeycomb-tracing no longer contains any dead links.
